version: '3'

services:

#Org1
  ca.org1.fabric.network:
    container_name: ca.org1.fabric.network
    image: hyperledger/fabric-ca:${CA_IMAGE_TAG}
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org1.fabric.network
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server/crypto-config/ca/ca.org1.fabric.network-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server/crypto-config/ca/secret.key
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server/crypto-config/ca/ca.org1.fabric.network-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server/crypto-config/ca/secret.key
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.fabric.network/ca/:/etc/hyperledger/fabric-ca-server/crypto-config/ca/
    ports:
      - 7054:7054
    networks:
      - fabric-network

  peer0.db.org1.fabric.network:
    container_name: peer0.db.org1.fabric.network
    image: hyperledger/fabric-couchdb:${COUCHDB_IMAGE_TAG}
    ports:
      - 5984:5984
    networks:
      - fabric-network

  peer0.org1.fabric.network:
    container_name: peer0.org1.fabric.network
    image: hyperledger/fabric-peer:${PEER_IMAGE_TAG}
    tty: true
    environment:
      # Identity
      - CORE_PEER_ID=peer0.org1.fabric.network
      - CORE_PEER_ADDRESS=peer0.org1.fabric.network:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/crypto-config/msp
      # TLS settings
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/crypto-config/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/crypto-config/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/crypto-config/tls/ca.crt
      # Gossips
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.fabric.network:7051
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      # Others
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - FABRIC_LOGGING_SPEC=debug
      - CORE_NEXT=true
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_fabric-network
      - GOPATH=/opt/gopath
      # World state
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=peer0.db.org1.fabric.network:5984
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org1.fabric.network/peers/peer0.org1.fabric.network/:/etc/hyperledger/fabric/crypto-config/
    ports:
      - 7051:7051
      - 7053:7053
    depends_on: 
      - orderer1.fabric.network
      - peer0.db.org1.fabric.network
    networks:
      - fabric-network

  cli.peer0.org1.fabric.network:
      container_name: cli.peer0.org1.fabric.network
      image: hyperledger/fabric-tools:${FABRIC_TOOL_IMAGE_TAG}
      tty: true
      environment:
        - GOPATH=/opt/gopath
        - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        - FABRIC_LOGGING_SPEC=debug
        # Identity
        - CORE_PEER_ID=peer0.org1.fabric.network
        - CORE_PEER_ADDRESS=peer0.org1.fabric.network:7051
        - CORE_PEER_LOCALMSPID=Org1MSP
        # TLS
        - CORE_PEER_TLS_ENABLED=true
        - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/crypto-config/tls/server.crt
        - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/crypto-config/tls/server.key
        - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/crypto-config/tls/ca.crt
        - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/crypto-config/users/Admin@org1.fabric.network/msp
        # Orderer
        - ORDERER=orderer1.fabric.network:7050
        - ORDERER_CA=/etc/hyperledger/fabric/crypto-config/orderer/msp/tlscacerts/tlsca.fabric.network-cert.pem
      working_dir: /opt/gopath/src/github.com/hyperledger/fabric
      command: /bin/bash
      volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org1.fabric.network/peers/peer0.org1.fabric.network/:/etc/hyperledger/fabric/crypto-config/
        - ./crypto-config/peerOrganizations/org1.fabric.network/users/:/etc/hyperledger/fabric/crypto-config/users/
        - ./crypto-config/ordererOrganizations/fabric.network/orderers/orderer1.fabric.network/:/etc/hyperledger/fabric/crypto-config/orderer/
        - ./channel-artefacts/:/opt/gopath/src/github.com/hyperledger/fabric/channel-artefacts/        
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/scripts
        - ${CHAINCODE_PATH}:/opt/gopath/src/github.com/hyperledger/fabric/chaincodes/
      depends_on:
        - peer0.org1.fabric.network
      networks:
        - fabric-network

#org2
  ca.org2.fabric.network:
    container_name: ca.org2.fabric.network
    image: hyperledger/fabric-ca:${CA_IMAGE_TAG}
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org2.fabric.network
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server/crypto-config/ca/ca.org2.fabric.network-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server/crypto-config/ca/secret.key
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server/crypto-config/ca/ca.org2.fabric.network-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server/crypto-config/ca/secret.key
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org2.fabric.network/ca/:/etc/hyperledger/fabric-ca-server/crypto-config/ca/
    ports:
      - 7154:7054
    networks:
      - fabric-network

  peer0.db.org2.fabric.network:
    container_name: peer0.db.org2.fabric.network
    image: hyperledger/fabric-couchdb:${COUCHDB_IMAGE_TAG}
    ports:
      - 5985:5984
    networks:
      - fabric-network

  peer0.org2.fabric.network:
    container_name: peer0.org2.fabric.network
    image: hyperledger/fabric-peer:${PEER_IMAGE_TAG}
    tty: true
    environment:
        # Identity
        - CORE_PEER_ID=peer0.org2.fabric.network
        - CORE_PEER_ADDRESS=peer0.org2.fabric.network:7051
        - CORE_PEER_LOCALMSPID=Org2MSP
        - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/crypto-config/msp
        # TLS
        - CORE_PEER_TLS_ENABLED=true
        - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/crypto-config/tls/server.crt
        - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/crypto-config/tls/server.key
        - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/crypto-config/tls/ca.crt
        # Gossip
        - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
        - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.fabric.network:7051
        - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.fabric.network:7051
        - CORE_PEER_GOSSIP_USELEADERELECTION=true
        - CORE_PEER_GOSSIP_ORGLEADER=false
        # Misc
        - CORE_PEER_ENDORSER_ENABLED=true
        - CORE_PEER_PROFILE_ENABLED=true
        - FABRIC_LOGGING_SPEC=debug
        - CORE_NEXT=true
        - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_fabric-network
        - GOPATH=/opt/gopath
        # World state
        - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
        - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=peer0.db.org2.fabric.network:5984
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org2.fabric.network/peers/peer0.org2.fabric.network/:/etc/hyperledger/fabric/crypto-config/
    ports:
      - 7061:7051
      - 7063:7053
    depends_on: 
      - orderer2.fabric.network
      - peer0.db.org2.fabric.network
    networks:
      - fabric-network

  cli.peer0.org2.fabric.network:
      container_name: cli.peer0.org2.fabric.network
      image: hyperledger/fabric-tools:${FABRIC_TOOL_IMAGE_TAG}
      tty: true
      environment:
        - GOPATH=/opt/gopath
        - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        - FABRIC_LOGGING_SPEC=debug
        - CORE_PEER_ID=peer0.org2.fabric.network
        - CORE_PEER_ADDRESS=peer0.org2.fabric.network:7051
        - CORE_PEER_LOCALMSPID=Org2MSP
        # TLS
        - CORE_PEER_TLS_ENABLED=true
        - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/crypto-config/tls/server.crt
        - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/crypto-config/tls/server.key
        - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/crypto-config/tls/ca.crt
        - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/crypto-config/users/Admin@org2.fabric.network/msp
        - ORDERER=orderer2.fabric.network:7050
        - ORDERER_CA=/etc/hyperledger/fabric/crypto-config/orderer/msp/tlscacerts/tlsca.fabric.network-cert.pem
      working_dir: /opt/gopath/src/github.com/hyperledger/fabric
      command: /bin/bash
      volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org2.fabric.network/peers/peer0.org2.fabric.network/:/etc/hyperledger/fabric/crypto-config/
        - ./crypto-config/peerOrganizations/org2.fabric.network/users/:/etc/hyperledger/fabric/crypto-config/users/
        - ./crypto-config/ordererOrganizations/fabric.network/orderers/orderer2.fabric.network/:/etc/hyperledger/fabric/crypto-config/orderer/
        - ./channel-artefacts/:/opt/gopath/src/github.com/hyperledger/fabric/channel-artefacts/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/scripts
        - ${CHAINCODE_PATH}:/opt/gopath/src/github.com/hyperledger/fabric/chaincodes/
      depends_on:
        - peer0.org2.fabric.network
      networks:
        - fabric-network

networks:
  fabric-network: